### ISSUE TITLE
Document Type, Document Type Associations, and Frameworks

### ISSUE THREAD

**Issue by mbakeranalecta** [oxygenxml/userguide#42]
The use of these terms in the docs is somewhat inconsistent and confusing. For instance, there is these passages:

> Practically you can associate an entire class of document (grouped logically 
> by some common features like namespace, root element name or filename) 
> to a bundle consisting of CSS stylesheets, validation schemas, catalog files, 
> new files templates, transformation scenarios and even custom actions. The 
> bundle is called document type and the association is called Document Type 
> Association or, more generically, framework.

and 

> A document type or framework is associated to an XML file according to a set of rules. 

"class of document" is not an XML term, but "document type" is. An XML document type is the type of exactly one document. Thus DITA may be a class of documents, but concept, task, and reference topics are all separate XML document types. Thus a bundle of DITA documents in a framework should not be called a "document type". It is a bundle of several related document types. 

Making "document types association" as synonym for framework is also problematic. One thing should have one name, or people will get confused. I would suggest that the bundle of functionality is a framework, and that a document types association is a set of rules that associate one or more documents with a framework.

I would propose the following definitions, therefore:

document type -- an XML document type

class of documents -- one or more related document types -- DITA topics, for instance.

framework -- a bundle of functionality related to a class of documents

document type association -- a set of rules that associate a document type with a framework

The use of these terms is not consistent in the interface either, but I think the bigger issue is in the docs.

Thoughts?

**Comment by StevenHiggs** [comment]
Personally, I think the "Document Type Association" preferences page should be called "Document Type Configuration" (or maybe "Framework Configuration"). That would alleviate some of the confusion and it would be more accurate for what the dialog box does since it has been greatly expanded from a rule association mechanism.

Regardless, while adding some glossary terms, I searched for all instances of these terms throughout the UG and made it more consistent, accurate, and less confusing.

**Comment by raducoravu** [comment]
I think we can probably close this issue anyway, we have an internal issue opened for this.
