### ISSUE TITLE
Need an Error Message Reference

### ISSUE THREAD

**Issue by mbakeranalecta** [oxygenxml/userguide#48]
Working on the Editor > Format  topic I noticed that it was indexed:

OutOfMemory
Out Of Memory
OutOfMemoryError

It took me a while to figure out why, but right down at the bottom there is a reference to changing a setting if you get an OutOfMemory error.

I did a search and there are quite a few topics that mention OutofMemory, but none of them are designed to tell you what things to check if you get and OutofMemory error. You might have to go through all of them, and even then you have to read a long way to find the reference in some of them. Chances are most people will call/write support rather than do that. 

We should think about creating an error message reference where people look up an error message and see all the things that could have caused it.

**Comment by StevenHiggs** [comment]
I consolidated these index terms into the two most appropriate topics that also include links to the others.
