### ISSUE TITLE
CSS3 Oxygen Extensions profile in Developer

### ISSUE THREAD

**Issue by mbakeranalecta** [oxygenxml/userguide#57]
Developer lets you select CSS3 with Oxygen Extensions profile in the CSS Validator preferences. However, the documentation of the Oxygen extensions is profiled out of the Developer docs. 

Of course, Developer cannot display the CSS with Oxygen Extensions (or any CSS) but it may still make sense to edit CSS in Developer. But if the Oxygen Extensions are supported for validation in Developer, doesn't the Developer user need documentation of those extensions?

**Comment by StevenHiggs** [comment]
Another sentence was added in the UG that is profiled for developer.
