### ISSUE TITLE
'Relax NG' in 'Schematron Preferences'

### ISSUE THREAD

**Issue by tgraham-antenna** [oxygenxml/userguide#62]
See https://github.com/oxygenxml/userguide/blob/master/DITA/topics/schematron-preferences-page.dita#L10

The 'Schematron Preferences' page directs the user to change settings in the 'Relax NG' section.

**Comment by raducoravu** [comment]
Thanks Tony, we'll rectify this. We have a private branch for the user manual and we'll update the public available repository after the Oxygen 17.0 release (april-may this year).
