### ISSUE TITLE
Filenames in image in DITA/tasks/dg-insert-section-action.dita

### ISSUE THREAD

**Issue by tgraham-antenna** [oxygenxml/userguide#64]
The text refers to '.png' files, but the graphic shows '.gif' filenames.

**Comment by raducoravu** [comment]
Thanks Tony, 

We'll rectify this inconsistency in the internal github repository.

**Comment by tgraham-antenna** [comment]
Radu,

On 13/03/2015 13:59, Radu Coravu wrote:
> Thanks Tony,
>
> We'll rectify this inconsistency in the internal github repository.

Is GitHub issues the best way to do this?  I've now seen that your 
online help allows comments.  Would that be better?

Regards,


Tony.

**Comment by raducoravu** [comment]
Hi Tony,

Both are good choices. Whatever you prefer :)
