### ISSUE TITLE
Question about part

### ISSUE THREAD

**Issue by ToshihikoMakita** [oxygenxml/userguide#66]
This bookmap has following structre:

```xml
  <frontmatter collection-type="sequence">
    <mapref href="productSbjSchemeVals.ditamap" type="subjectScheme"/>
    <booklists>
      <toc/>
    </booklists>
    <notices href="topics/copyright.dita"/>
  </frontmatter>
  <part>
    <mapref href="keydefs.ditamap"/>
    <mapref href="reusables/reusables.ditamap"/>
  </part>
  <part collection-type="sequence">
    <chapter href="chapter-introduction.ditamap" collection-type="unordered" format="ditamap"/>
    <chapter href="chapter-installation.ditamap" collection-type="sequence" format="ditamap"/>
    <chapter href="chapter-getting-started.ditamap" product="author editor"
      collection-type="sequence" format="ditamap"/>
    ...
  </part>
```

Are there any meaning of using part? The part elements are used to divide keydefs and contents. 
According to the DITA specification part is defined as follows:

> The <part> element references a part topic or a map that references part topics for the book.

The part element constructs the explicit document structure. So I think part elements with no @navtitle nor topicmeta/navtite nor topic/title is meaningless. The keydef part should be moved into frontmatter.

Please give me your opinion.

**Comment by raducoravu** [comment]
Dear Toshihiko Makita,

Thanks for the input, I agree.

Our current development branch of the user's manual (which will be uploaded to the public repository when Oxygen 17.1 is released) already removed the usage of <part> in the map.

The main reason for the <part> element there was that we wanted to add <mapref>s to the subject scheme and to the map which refers various reusable topics. And you cannot add <mapref> directly inside a bookmap.
But we moved those maprefs in the frontmatter part.

Regards,
Radu
