### ISSUE TITLE
Index comments

### ISSUE THREAD

**Issue by tgraham-antenna** [oxygenxml/userguide#68]
With oXygen 17.1:

1. It doesn't make sense to me that 'Configure the Application [1] ' points to "Network Connection Settings Preferences".
1. "Comparing and Merging Documents(Compare Directories tool" could do with a space after "Documents" and also a ")".
1. I spent a long time thinking that "Comparing and Merging Documents(Compare Directories tool" was "Documents(Compare Directories tool" before working out that the preceding "Comparing and Merging" was part of the same entry.
1. "Configure Application" and "Configure the Application" are very similar.
1. "Compare Files tool Compare Directories tool" appears to not make much sense.
1. "Trusted Hosts Preferences" doesn't appear to have an index entry, though the other network connection settings preferences all seem to.

**Comment by bogdangoreci** [comment]
@tgraham-antenna , you are correct, we'll need to review the entire index hierarchy. I'll add an issue in our internal bug tracking system and close this one.
